server {
    listen 80;

    # 静态文件服务
    location /_next/ {
        root /usr/share/nginx/html;
        try_files $uri /_next/$uri;
    }

    # 指定 /new-safe/load 默认文件为 load.html
    location = /new-safe/load {
        root /usr/share/nginx/html;
	index load.html;
        try_files /new-safe/load.html =404;
    }
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}

