/**
 * This file was auto-generated. Do not make direct changes.
 */

import _createClient from "openapi-fetch";
import type { ClientMethod, FetchOptions } from "openapi-fetch";
import type {
  FilterKeys,
  HttpMethod,
  MediaType,
  PathsWithMethod,
} from "openapi-typescript-helpers";

import { getClient } from "./client";
import type { paths } from "./schema";

type ExtractOptions<
  Method extends HttpMethod,
  Path extends keyof paths,
> = FetchOptions<FilterKeys<paths[Path], Method>>;

async function clientRequest<
  Method extends Extract<keyof paths[keyof paths], HttpMethod>,
  Path extends PathsWithMethod<paths, Method>,
  Options extends ExtractOptions<Method, Path>,
>(method: Method, path: Path, options: Options) {
  const client = getClient();
  const _method = method.toUpperCase() as Uppercase<Method>;
  // @ts-expect-error - paths is generated by openapi-typescript
  const fn = client[_method] as ClientMethod<paths, Method, MediaType>;
  const { data, error } = await fn(path, options);

  if (error || !data) {
    throw error;
  }
  return data;
}

export type getAbout =
  paths["/about"]["get"]["responses"][200]["content"]["application/json"];
export async function getAbout(
  options: ExtractOptions<"get", "/about">,
): Promise<getAbout> {
  return clientRequest("get", "/about", options);
}

export type createAccount =
  paths["/v1/accounts"]["post"]["responses"][200]["content"]["application/json"];
export async function createAccount(
  options: ExtractOptions<"post", "/v1/accounts">,
): Promise<createAccount> {
  return clientRequest("post", "/v1/accounts", options);
}

export type getDataTypes =
  paths["/v1/accounts/data-types"]["get"]["responses"][200]["content"]["application/json"];
export async function getDataTypes(
  options: ExtractOptions<"get", "/v1/accounts/data-types">,
): Promise<getDataTypes> {
  return clientRequest("get", "/v1/accounts/data-types", options);
}

export type getAccountDataSettings =
  paths["/v1/accounts/{address}/data-settings"]["get"]["responses"][200]["content"]["application/json"];
export async function getAccountDataSettings(
  options: ExtractOptions<"get", "/v1/accounts/{address}/data-settings">,
): Promise<getAccountDataSettings> {
  return clientRequest("get", "/v1/accounts/{address}/data-settings", options);
}

export type upsertAccountDataSettings =
  paths["/v1/accounts/{address}/data-settings"]["put"]["responses"][200]["content"]["application/json"];
export async function upsertAccountDataSettings(
  options: ExtractOptions<"put", "/v1/accounts/{address}/data-settings">,
): Promise<upsertAccountDataSettings> {
  return clientRequest("put", "/v1/accounts/{address}/data-settings", options);
}

export type getAccount =
  paths["/v1/accounts/{address}"]["get"]["responses"][200]["content"]["application/json"];
export async function getAccount(
  options: ExtractOptions<"get", "/v1/accounts/{address}">,
): Promise<getAccount> {
  return clientRequest("get", "/v1/accounts/{address}", options);
}

export type deleteAccount = never;
export async function deleteAccount(
  options: ExtractOptions<"delete", "/v1/accounts/{address}">,
): Promise<deleteAccount> {
  return clientRequest("delete", "/v1/accounts/{address}", options);
}

export type getCounterfactualSafe =
  paths["/v1/accounts/{address}/counterfactual-safes/{chainId}/{predictedAddress}"]["get"]["responses"][200]["content"]["application/json"];
export async function getCounterfactualSafe(
  options: ExtractOptions<
    "get",
    "/v1/accounts/{address}/counterfactual-safes/{chainId}/{predictedAddress}"
  >,
): Promise<getCounterfactualSafe> {
  return clientRequest(
    "get",
    "/v1/accounts/{address}/counterfactual-safes/{chainId}/{predictedAddress}",
    options,
  );
}

export type deleteCounterfactualSafe = never;
export async function deleteCounterfactualSafe(
  options: ExtractOptions<
    "delete",
    "/v1/accounts/{address}/counterfactual-safes/{chainId}/{predictedAddress}"
  >,
): Promise<deleteCounterfactualSafe> {
  return clientRequest(
    "delete",
    "/v1/accounts/{address}/counterfactual-safes/{chainId}/{predictedAddress}",
    options,
  );
}

export type getCounterfactualSafes =
  paths["/v1/accounts/{address}/counterfactual-safes"]["get"]["responses"][200]["content"]["application/json"];
export async function getCounterfactualSafes(
  options: ExtractOptions<"get", "/v1/accounts/{address}/counterfactual-safes">,
): Promise<getCounterfactualSafes> {
  return clientRequest(
    "get",
    "/v1/accounts/{address}/counterfactual-safes",
    options,
  );
}

export type createCounterfactualSafe =
  paths["/v1/accounts/{address}/counterfactual-safes"]["put"]["responses"][200]["content"]["application/json"];
export async function createCounterfactualSafe(
  options: ExtractOptions<"put", "/v1/accounts/{address}/counterfactual-safes">,
): Promise<createCounterfactualSafe> {
  return clientRequest(
    "put",
    "/v1/accounts/{address}/counterfactual-safes",
    options,
  );
}

export type deleteCounterfactualSafes = never;
export async function deleteCounterfactualSafes(
  options: ExtractOptions<
    "delete",
    "/v1/accounts/{address}/counterfactual-safes"
  >,
): Promise<deleteCounterfactualSafes> {
  return clientRequest(
    "delete",
    "/v1/accounts/{address}/counterfactual-safes",
    options,
  );
}

export type getNonce =
  paths["/v1/auth/nonce"]["get"]["responses"][200]["content"]["application/json"];
export async function getNonce(
  options: ExtractOptions<"get", "/v1/auth/nonce">,
): Promise<getNonce> {
  return clientRequest("get", "/v1/auth/nonce", options);
}

export type verify = never;
export async function verify(
  options: ExtractOptions<"post", "/v1/auth/verify">,
): Promise<verify> {
  return clientRequest("post", "/v1/auth/verify", options);
}

export type getBalances =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/balances/{fiatCode}"]["get"]["responses"][200]["content"]["application/json"];
export async function getBalances(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/balances/{fiatCode}"
  >,
): Promise<getBalances> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/balances/{fiatCode}",
    options,
  );
}

export type getSupportedFiatCodes = never;
export async function getSupportedFiatCodes(
  options: ExtractOptions<"get", "/v1/balances/supported-fiat-codes">,
): Promise<getSupportedFiatCodes> {
  return clientRequest("get", "/v1/balances/supported-fiat-codes", options);
}

export type getChains =
  paths["/v1/chains"]["get"]["responses"][200]["content"]["application/json"];
export async function getChains(
  options: ExtractOptions<"get", "/v1/chains">,
): Promise<getChains> {
  return clientRequest("get", "/v1/chains", options);
}

export type getChain =
  paths["/v1/chains/{chainId}"]["get"]["responses"][200]["content"]["application/json"];
export async function getChain(
  options: ExtractOptions<"get", "/v1/chains/{chainId}">,
): Promise<getChain> {
  return clientRequest("get", "/v1/chains/{chainId}", options);
}

export type getAboutChain =
  paths["/v1/chains/{chainId}/about"]["get"]["responses"][200]["content"]["application/json"];
export async function getAboutChain(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/about">,
): Promise<getAboutChain> {
  return clientRequest("get", "/v1/chains/{chainId}/about", options);
}

export type getBackbone =
  paths["/v1/chains/{chainId}/about/backbone"]["get"]["responses"][200]["content"]["application/json"];
export async function getBackbone(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/about/backbone">,
): Promise<getBackbone> {
  return clientRequest("get", "/v1/chains/{chainId}/about/backbone", options);
}

export type getMasterCopies =
  paths["/v1/chains/{chainId}/about/master-copies"]["get"]["responses"][200]["content"]["application/json"];
export async function getMasterCopies(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/about/master-copies">,
): Promise<getMasterCopies> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/about/master-copies",
    options,
  );
}

export type getIndexingStatus =
  paths["/v1/chains/{chainId}/about/indexing"]["get"]["responses"][200]["content"]["application/json"];
export async function getIndexingStatus(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/about/indexing">,
): Promise<getIndexingStatus> {
  return clientRequest("get", "/v1/chains/{chainId}/about/indexing", options);
}

export type getCollectibles =
  paths["/v2/chains/{chainId}/safes/{safeAddress}/collectibles"]["get"]["responses"][200]["content"]["application/json"];
export async function getCollectibles(
  options: ExtractOptions<
    "get",
    "/v2/chains/{chainId}/safes/{safeAddress}/collectibles"
  >,
): Promise<getCollectibles> {
  return clientRequest(
    "get",
    "/v2/chains/{chainId}/safes/{safeAddress}/collectibles",
    options,
  );
}

export type getCampaigns =
  paths["/v1/community/campaigns"]["get"]["responses"][200]["content"]["application/json"];
export async function getCampaigns(
  options: ExtractOptions<"get", "/v1/community/campaigns">,
): Promise<getCampaigns> {
  return clientRequest("get", "/v1/community/campaigns", options);
}

export type getCampaignById =
  paths["/v1/community/campaigns/{resourceId}"]["get"]["responses"][200]["content"]["application/json"];
export async function getCampaignById(
  options: ExtractOptions<"get", "/v1/community/campaigns/{resourceId}">,
): Promise<getCampaignById> {
  return clientRequest("get", "/v1/community/campaigns/{resourceId}", options);
}

export type getCampaignActivities = never;
export async function getCampaignActivities(
  options: ExtractOptions<
    "get",
    "/v1/community/campaigns/{resourceId}/activities"
  >,
): Promise<getCampaignActivities> {
  return clientRequest(
    "get",
    "/v1/community/campaigns/{resourceId}/activities",
    options,
  );
}

export type getCampaignLeaderboard =
  paths["/v1/community/campaigns/{resourceId}/leaderboard"]["get"]["responses"][200]["content"]["application/json"];
export async function getCampaignLeaderboard(
  options: ExtractOptions<
    "get",
    "/v1/community/campaigns/{resourceId}/leaderboard"
  >,
): Promise<getCampaignLeaderboard> {
  return clientRequest(
    "get",
    "/v1/community/campaigns/{resourceId}/leaderboard",
    options,
  );
}

export type getCampaignRank =
  paths["/v1/community/campaigns/{resourceId}/leaderboard/{safeAddress}"]["get"]["responses"][200]["content"]["application/json"];
export async function getCampaignRank(
  options: ExtractOptions<
    "get",
    "/v1/community/campaigns/{resourceId}/leaderboard/{safeAddress}"
  >,
): Promise<getCampaignRank> {
  return clientRequest(
    "get",
    "/v1/community/campaigns/{resourceId}/leaderboard/{safeAddress}",
    options,
  );
}

export type getLeaderboard =
  paths["/v1/community/locking/leaderboard"]["get"]["responses"][200]["content"]["application/json"];
export async function getLeaderboard(
  options: ExtractOptions<"get", "/v1/community/locking/leaderboard">,
): Promise<getLeaderboard> {
  return clientRequest("get", "/v1/community/locking/leaderboard", options);
}

export type getLockingRank =
  paths["/v1/community/locking/{safeAddress}/rank"]["get"]["responses"][200]["content"]["application/json"];
export async function getLockingRank(
  options: ExtractOptions<"get", "/v1/community/locking/{safeAddress}/rank">,
): Promise<getLockingRank> {
  return clientRequest(
    "get",
    "/v1/community/locking/{safeAddress}/rank",
    options,
  );
}

export type getLockingHistory =
  paths["/v1/community/locking/{safeAddress}/history"]["get"]["responses"][200]["content"]["application/json"];
export async function getLockingHistory(
  options: ExtractOptions<"get", "/v1/community/locking/{safeAddress}/history">,
): Promise<getLockingHistory> {
  return clientRequest(
    "get",
    "/v1/community/locking/{safeAddress}/history",
    options,
  );
}

export type getContract =
  paths["/v1/chains/{chainId}/contracts/{contractAddress}"]["get"]["responses"][200]["content"]["application/json"];
export async function getContract(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/contracts/{contractAddress}"
  >,
): Promise<getContract> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/contracts/{contractAddress}",
    options,
  );
}

export type getDataDecoded =
  paths["/v1/chains/{chainId}/data-decoder"]["post"]["responses"][200]["content"]["application/json"];
export async function getDataDecoded(
  options: ExtractOptions<"post", "/v1/chains/{chainId}/data-decoder">,
): Promise<getDataDecoded> {
  return clientRequest("post", "/v1/chains/{chainId}/data-decoder", options);
}

export type getDelegates =
  paths["/v1/chains/{chainId}/delegates"]["get"]["responses"][200]["content"]["application/json"];
export async function getDelegates(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/delegates">,
): Promise<getDelegates> {
  return clientRequest("get", "/v1/chains/{chainId}/delegates", options);
}

export type postDelegate = never;
export async function postDelegate(
  options: ExtractOptions<"post", "/v1/chains/{chainId}/delegates">,
): Promise<postDelegate> {
  return clientRequest("post", "/v1/chains/{chainId}/delegates", options);
}

export type deleteDelegate = never;
export async function deleteDelegate(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/delegates/{delegateAddress}"
  >,
): Promise<deleteDelegate> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/delegates/{delegateAddress}",
    options,
  );
}

export type deleteSafeDelegate = never;
export async function deleteSafeDelegate(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/safes/{safeAddress}/delegates/{delegateAddress}"
  >,
): Promise<deleteSafeDelegate> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/safes/{safeAddress}/delegates/{delegateAddress}",
    options,
  );
}

export type getDelegatesV2 =
  paths["/v2/chains/{chainId}/delegates"]["get"]["responses"][200]["content"]["application/json"];
export async function getDelegatesV2(
  options: ExtractOptions<"get", "/v2/chains/{chainId}/delegates">,
): Promise<getDelegatesV2> {
  return clientRequest("get", "/v2/chains/{chainId}/delegates", options);
}

export type postDelegateV2 = never;
export async function postDelegateV2(
  options: ExtractOptions<"post", "/v2/chains/{chainId}/delegates">,
): Promise<postDelegateV2> {
  return clientRequest("post", "/v2/chains/{chainId}/delegates", options);
}

export type deleteDelegateV2 = never;
export async function deleteDelegateV2(
  options: ExtractOptions<
    "delete",
    "/v2/chains/{chainId}/delegates/{delegateAddress}"
  >,
): Promise<deleteDelegateV2> {
  return clientRequest(
    "delete",
    "/v2/chains/{chainId}/delegates/{delegateAddress}",
    options,
  );
}

export type addRecoveryModule = never;
export async function addRecoveryModule(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/recovery"
  >,
): Promise<addRecoveryModule> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/recovery",
    options,
  );
}

export type deleteRecoveryModule = never;
export async function deleteRecoveryModule(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/safes/{safeAddress}/recovery/{moduleAddress}"
  >,
): Promise<deleteRecoveryModule> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/safes/{safeAddress}/recovery/{moduleAddress}",
    options,
  );
}

export type getEstimation =
  paths["/v2/chains/{chainId}/safes/{address}/multisig-transactions/estimations"]["post"]["responses"][200]["content"]["application/json"];
export async function getEstimation(
  options: ExtractOptions<
    "post",
    "/v2/chains/{chainId}/safes/{address}/multisig-transactions/estimations"
  >,
): Promise<getEstimation> {
  return clientRequest(
    "post",
    "/v2/chains/{chainId}/safes/{address}/multisig-transactions/estimations",
    options,
  );
}

export type getMessageByHash =
  paths["/v1/chains/{chainId}/messages/{messageHash}"]["get"]["responses"][200]["content"]["application/json"];
export async function getMessageByHash(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/messages/{messageHash}">,
): Promise<getMessageByHash> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/messages/{messageHash}",
    options,
  );
}

export type getMessagesBySafe =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/messages"]["get"]["responses"][200]["content"]["application/json"];
export async function getMessagesBySafe(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/messages"
  >,
): Promise<getMessagesBySafe> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/messages",
    options,
  );
}

export type createMessage = never;
export async function createMessage(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/messages"
  >,
): Promise<createMessage> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/messages",
    options,
  );
}

export type updateMessageSignature = never;
export async function updateMessageSignature(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/messages/{messageHash}/signatures"
  >,
): Promise<updateMessageSignature> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/messages/{messageHash}/signatures",
    options,
  );
}

export type registerDevice = never;
export async function registerDevice(
  options: ExtractOptions<"post", "/v1/register/notifications">,
): Promise<registerDevice> {
  return clientRequest("post", "/v1/register/notifications", options);
}

export type unregisterDevice = never;
export async function unregisterDevice(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/notifications/devices/{uuid}"
  >,
): Promise<unregisterDevice> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/notifications/devices/{uuid}",
    options,
  );
}

export type unregisterSafe = never;
export async function unregisterSafe(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/notifications/devices/{uuid}/safes/{safeAddress}"
  >,
): Promise<unregisterSafe> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/notifications/devices/{uuid}/safes/{safeAddress}",
    options,
  );
}

export type getSafesByOwner =
  paths["/v1/chains/{chainId}/owners/{ownerAddress}/safes"]["get"]["responses"][200]["content"]["application/json"];
export async function getSafesByOwner(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/owners/{ownerAddress}/safes"
  >,
): Promise<getSafesByOwner> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/owners/{ownerAddress}/safes",
    options,
  );
}

export type getAllSafesByOwner =
  paths["/v1/owners/{ownerAddress}/safes"]["get"]["responses"][200]["content"]["application/json"];
export async function getAllSafesByOwner(
  options: ExtractOptions<"get", "/v1/owners/{ownerAddress}/safes">,
): Promise<getAllSafesByOwner> {
  return clientRequest("get", "/v1/owners/{ownerAddress}/safes", options);
}

export type relay = never;
export async function relay(
  options: ExtractOptions<"post", "/v1/chains/{chainId}/relay">,
): Promise<relay> {
  return clientRequest("post", "/v1/chains/{chainId}/relay", options);
}

export type getRelaysRemaining = never;
export async function getRelaysRemaining(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/relay/{safeAddress}">,
): Promise<getRelaysRemaining> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/relay/{safeAddress}",
    options,
  );
}

export type getSafeApps =
  paths["/v1/chains/{chainId}/safe-apps"]["get"]["responses"][200]["content"]["application/json"];
export async function getSafeApps(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/safe-apps">,
): Promise<getSafeApps> {
  return clientRequest("get", "/v1/chains/{chainId}/safe-apps", options);
}

export type getSafe =
  paths["/v1/chains/{chainId}/safes/{safeAddress}"]["get"]["responses"][200]["content"]["application/json"];
export async function getSafe(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/safes/{safeAddress}">,
): Promise<getSafe> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}",
    options,
  );
}

export type getNonces =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/nonces"]["get"]["responses"][200]["content"]["application/json"];
export async function getNonces(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/nonces"
  >,
): Promise<getNonces> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/nonces",
    options,
  );
}

export type getSafeOverview = never;
export async function getSafeOverview(
  options: ExtractOptions<"get", "/v1/safes">,
): Promise<getSafeOverview> {
  return clientRequest("get", "/v1/safes", options);
}

export type getSubmission =
  paths["/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions"]["get"]["responses"][200]["content"]["application/json"];
export async function getSubmission(
  options: ExtractOptions<
    "get",
    "/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions"
  >,
): Promise<getSubmission> {
  return clientRequest(
    "get",
    "/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions",
    options,
  );
}

export type createSubmission =
  paths["/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions"]["post"]["responses"][201]["content"]["application/json"];
export async function createSubmission(
  options: ExtractOptions<
    "post",
    "/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions"
  >,
): Promise<createSubmission> {
  return clientRequest(
    "post",
    "/v1/targeted-messaging/outreaches/{outreachId}/chains/{chainId}/safes/{safeAddress}/signers/{signerAddress}/submissions",
    options,
  );
}

export type getTransactionById =
  paths["/v1/chains/{chainId}/transactions/{id}"]["get"]["responses"][200]["content"]["application/json"];
export async function getTransactionById(
  options: ExtractOptions<"get", "/v1/chains/{chainId}/transactions/{id}">,
): Promise<getTransactionById> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/transactions/{id}",
    options,
  );
}

export type getMultisigTransactions =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/multisig-transactions"]["get"]["responses"][200]["content"]["application/json"];
export async function getMultisigTransactions(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/multisig-transactions"
  >,
): Promise<getMultisigTransactions> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/multisig-transactions",
    options,
  );
}

export type deleteTransaction = never;
export async function deleteTransaction(
  options: ExtractOptions<
    "delete",
    "/v1/chains/{chainId}/transactions/{safeTxHash}"
  >,
): Promise<deleteTransaction> {
  return clientRequest(
    "delete",
    "/v1/chains/{chainId}/transactions/{safeTxHash}",
    options,
  );
}

export type getModuleTransactions =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/module-transactions"]["get"]["responses"][200]["content"]["application/json"];
export async function getModuleTransactions(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/module-transactions"
  >,
): Promise<getModuleTransactions> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/module-transactions",
    options,
  );
}

export type addConfirmation =
  paths["/v1/chains/{chainId}/transactions/{safeTxHash}/confirmations"]["post"]["responses"][200]["content"]["application/json"];
export async function addConfirmation(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/transactions/{safeTxHash}/confirmations"
  >,
): Promise<addConfirmation> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/transactions/{safeTxHash}/confirmations",
    options,
  );
}

export type getIncomingTransfers =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/incoming-transfers"]["get"]["responses"][200]["content"]["application/json"];
export async function getIncomingTransfers(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/incoming-transfers"
  >,
): Promise<getIncomingTransfers> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/incoming-transfers",
    options,
  );
}

export type previewTransaction =
  paths["/v1/chains/{chainId}/transactions/{safeAddress}/preview"]["post"]["responses"][200]["content"]["application/json"];
export async function previewTransaction(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/transactions/{safeAddress}/preview"
  >,
): Promise<previewTransaction> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/transactions/{safeAddress}/preview",
    options,
  );
}

export type getTransactionQueue =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/transactions/queued"]["get"]["responses"][200]["content"]["application/json"];
export async function getTransactionQueue(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/queued"
  >,
): Promise<getTransactionQueue> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/queued",
    options,
  );
}

export type getTransactionsHistory =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/transactions/history"]["get"]["responses"][200]["content"]["application/json"];
export async function getTransactionsHistory(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/history"
  >,
): Promise<getTransactionsHistory> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/history",
    options,
  );
}

export type proposeTransaction =
  paths["/v1/chains/{chainId}/transactions/{safeAddress}/propose"]["post"]["responses"][200]["content"]["application/json"];
export async function proposeTransaction(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/transactions/{safeAddress}/propose"
  >,
): Promise<proposeTransaction> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/transactions/{safeAddress}/propose",
    options,
  );
}

export type getCreationTransaction =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/transactions/creation"]["get"]["responses"][200]["content"]["application/json"];
export async function getCreationTransaction(
  options: ExtractOptions<
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/creation"
  >,
): Promise<getCreationTransaction> {
  return clientRequest(
    "get",
    "/v1/chains/{chainId}/safes/{safeAddress}/transactions/creation",
    options,
  );
}

export type getTransactionConfirmationView =
  paths["/v1/chains/{chainId}/safes/{safeAddress}/views/transaction-confirmation"]["post"]["responses"][200]["content"]["application/json"];
export async function getTransactionConfirmationView(
  options: ExtractOptions<
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/views/transaction-confirmation"
  >,
): Promise<getTransactionConfirmationView> {
  return clientRequest(
    "post",
    "/v1/chains/{chainId}/safes/{safeAddress}/views/transaction-confirmation",
    options,
  );
}
