import openapiTS, { astToString, Method, OpenAPI3 } from "openapi-typescript";

import {
  CLIENT_FILE_NAME,
  PROD_SWAGGER_URL,
  SCHEMA_FILE_NAME,
  SDK_FILE_NAME,
  STAGING_SWAGGER_URL,
} from "./constants";

/**
 * Fetches the Swagger UI init script
 * @returns - Swagger UI init script
 */
export async function getSwaggerUiInit(): Promise<string> {
  const res = await fetch(`${STAGING_SWAGGER_URL}/api/swagger-ui-init.js`);
  if (!res.ok) {
    throw new Error("Failed to fetch");
  }
  return res.text();
}

/**
 * Extracts the Swagger schema from the Swagger UI init script
 * @param swaggerUiInit - Swagger UI init script
 * @returns - Swagger schema object
 */
export function extractSwaggerSchema(swaggerUiInit: string): OpenAPI3 {
  const optionsMatch = swaggerUiInit.match(/let options = (\{[\s\S]*?\});/);
  if (!optionsMatch?.[1]) {
    throw new Error('No "options" object found');
  }
  const options = JSON.parse(optionsMatch[1]);
  return options.swaggerDoc;
}

/**
 * Parses the Swagger schema into openapiTS object
 * @param swaggerSchema - Swagger schema object
 * @returns - openapiTS object
 */
export async function parseSwaggerSchema(
  swaggerSchema: OpenAPI3,
): Promise<string> {
  const nodes = await openapiTS(swaggerSchema);
  return astToString(nodes);
}

/**
 * Factory for Safe Client Gateway-typed client and singleton
 * @returns - Typed factory and singleton
 */
export function getClient(): string {
  const imports = [
    "import _createClient from 'openapi-fetch';",
    `import type { paths } from './${SCHEMA_FILE_NAME}';`,
  ];

  // Typed factory, singleton, singleton getter, singleton URL updater
  const client = [
    "const createClient = _createClient<paths>;",
    `let _client = createClient({
  baseUrl: '${PROD_SWAGGER_URL}',
})`,
    `export function getClient() {
  return _client
}`,
    `export function setBaseUrl(baseUrl: string) {
  _client = createClient({ baseUrl });
}`,
  ];

  return [...imports, ...client].join("\n\n");
}

/**
 * Typed path-specific wrappers for fetching from the Safe Client Gateway
 * @param swaggerSchema - Swagger schema object
 * @returns - Typed wrapper functions for each path
 */
export function getWrappers(swaggerSchema: OpenAPI3): string {
  if (!swaggerSchema.paths) {
    throw new Error("Failed to find paths object");
  }

  const imports = [
    `import _createClient from 'openapi-fetch';
import type { ClientMethod, FetchOptions } from "openapi-fetch";
import type { FilterKeys, HttpMethod, MediaType, PathsWithMethod } from "openapi-typescript-helpers";`,
    `import { getClient } from './client';
import type { paths } from './${SCHEMA_FILE_NAME}';`,
  ];

  // Wrapper to return `data` and throw `error` if applicable
  const clientWrapper = [
    `type ExtractOptions<
  Method extends HttpMethod,
  Path extends keyof paths,
> = FetchOptions<FilterKeys<paths[Path], Method>>;`,
    `async function clientRequest<
  Method extends Extract<keyof paths[keyof paths], HttpMethod>,
  Path extends PathsWithMethod<paths, Method>,
  Options extends ExtractOptions<Method, Path>,
>(method: Method, path: Path, options: Options) {
  const client = getClient();
  const _method = method.toUpperCase() as Uppercase<Method>;
  // @ts-expect-error - paths is generated by openapi-typescript
  const fn = client[_method] as ClientMethod<paths, Method, MediaType>;
  const { data, error } = await fn(path, options);

  if (error || !data) {
    throw error;
  }
  return data;
}`,
  ];

  // Path-specific wrappers with associated types
  const wrappers = Object.keys(swaggerSchema.paths).flatMap((path) => {
    const pathItemObj = swaggerSchema.paths?.[path];
    if (!pathItemObj || "$ref" in pathItemObj) {
      throw new Error("No PathItemObject in path(s)");
    }

    // get, post, put, etc.
    const methods = ((): Array<Method> => {
      const isFetchMethod = (method: string): method is Method => {
        // prettier-ignore
        return ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'].includes(method);
      };

      const methods = Object.keys(pathItemObj);
      if (!methods.every(isFetchMethod)) {
        throw new Error(`Invalid fetch methods: ${methods.join(", ")}`);
      }
      return methods;
    })();

    return methods.map((method) => {
      const operationObject = pathItemObj[method];
      if (!operationObject || !("operationId" in operationObject)) {
        throw new Error(`No operation object for ${path}`);
      }

      // e.g. AboutController_getAbout
      const operationId = operationObject.operationId;
      if (!operationId) {
        throw new Error(`No operationId for ${path}`);
      }

      // e.g. ['AboutController, 'getAbout']
      const [controller, methodName] = operationId.split("_");
      if (!controller || !methodName) {
        throw new Error(`Invalid operationId: ${operationId}`);
      }

      // Prevent duplicated by appending controller version to method
      const wrapperName = ((): string => {
        const versionMatch = controller.match(/v\d+/i);
        return versionMatch?.[0] ? methodName + versionMatch[0] : methodName;
      })();

      // Wrapper-named return types for convenience/grouping of unions
      // e.g. type getAbout = paths["/about"]["get"]["responses"]["200"]["content"]["application/json"];
      const returnType = (() => {
        if (!operationObject.responses) {
          return "never";
        }

        const statusCodes = Object.keys(operationObject.responses);
        if (statusCodes.length === 0 || statusCodes.length > 1) {
          throw new Error(`Invalid status codes for ${path}: ${statusCodes}`);
        }

        const statusCode = statusCodes[0];
        const response = operationObject.responses[statusCode];
        if (!("content" in response)) {
          return "never";
        }

        const mediaType = "application/json";
        if (!response.content?.[mediaType]) {
          throw new Error(`No ${mediaType} for ${path}`);
        }

        return `paths["${path}"]["${method}"]["responses"][${statusCode}]["content"]["${mediaType}"]`;
      })();

      return `export type ${wrapperName} = ${returnType};
export async function ${wrapperName}(options: ExtractOptions<"${method}", "${path}">): Promise<${wrapperName}> {
  return clientRequest("${method}", "${path}", options);
}`;
    });
  });

  return [...imports, ...clientWrapper, ...wrappers].join("\n\n");
}

/**
 * Re-exports client, schema and SDK for convenience
 * @returns - Re-exported schema and SDK
 */
export function getBarrel(): string {
  return [CLIENT_FILE_NAME, SCHEMA_FILE_NAME, SDK_FILE_NAME]
    .map((file) => {
      return `export * from './${file}';`;
    })
    .join("\n");
}
